--------------------------------------------------------
--  File created - Thursday-May-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "ITEM" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"QUANTITY_IN_STOCK" NUMBER(*,0), 
	"PRICE" NUMBER(4,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_TABLE
--------------------------------------------------------

  CREATE TABLE "ORDER_TABLE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ITEM_ID" NUMBER(*,0) DEFAULT '0', 
	"QUANTITY" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ITEM
SET DEFINE OFF;
Insert into ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (1,'Bevita',16,50);
Insert into ITEM (ID,NAME,QUANTITY_IN_STOCK,PRICE) values (2,'Ginger Ale',5,4);
REM INSERTING into ORDER_TABLE
SET DEFINE OFF;
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (6,1,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (7,2,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (8,1,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (9,1,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (10,1,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (11,1,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (12,2,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (21,1,10);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (22,2,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (23,1,4);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (24,1,4);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (25,2,3);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (26,1,3);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (27,2,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (28,1,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (29,2,3);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (30,1,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (31,2,3);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (41,1,4);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (42,2,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (43,1,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (44,2,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (45,1,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (46,2,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (47,1,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (48,2,3);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (49,1,5);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (50,2,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (51,1,2);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (52,1,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (53,1,1);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (54,1,4);
Insert into ORDER_TABLE (ID,ITEM_ID,QUANTITY) values (55,2,5);
--------------------------------------------------------
--  DDL for Index ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITEM_PK" ON "ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007372
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007372" ON "ITEM" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORDER_PK" ON "ORDER_TABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "ITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ITEM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ITEM" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ITEM" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "ORDER_TABLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ORDER_TABLE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ORDER_TABLE" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
